const { SlashCommandBuilder, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, PermissionFlagsBits } = require('discord.js');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('free-key')
        .setDescription('Sets up the free key panel (English).')
        .setDefaultMemberPermissions(PermissionFlagsBits.Administrator),

    async execute(interaction) {
        await interaction.deferReply({ ephemeral: true });

        const embed = new EmbedBuilder()
            .setColor('#2B2D31')
            .setTitle('Free Access Panel')
            .setDescription(`🚀 **System -->** \`Luas Free\`\n` +
                            `🆔 **Access Type -->** \`Public\`\n` +
                            `🪄 **Duration -->** \`Lifetime\`\n` +
                            `👑 **Status -->** \`Active & Working\`\n` +
                            `📝 **How to get? -->** \`Click the button below\`\n` +
                            `⏰ **Panel Setup Time -->** <t:${Math.floor(Date.now() / 1000)}:F>\n\n` +
                            `❗️ \`Warning!!\` __**THE KEY YOU RECEIVE WILL BE LOCKED TO YOUR HARDWARE (HWID)**__`)
            .setThumbnail(interaction.guild.iconURL({ dynamic: true }))
            .setFooter({ text: 'Luas • Automatic Delivery System', iconURL: interaction.guild.iconURL() });

        const row = new ActionRowBuilder().addComponents(
            new ButtonBuilder()
                .setCustomId('get_free_key_en')
                .setLabel('🎁 Get Free Key')
                .setStyle(ButtonStyle.Success)
        );

        await interaction.channel.send({ embeds: [embed], components: [row] });
        await interaction.editReply({ content: '✅ **Free key panel has been successfully set up!**' });
    },

    async handleButton(interaction, UserModel) {
        if (interaction.customId !== 'get_free_key_en') return;
        await interaction.deferReply({ ephemeral: true });

        try {
            let existingUser = await UserModel.findOne({ discordId: interaction.user.id, plan: 'free' });
            if (existingUser) {
                return interaction.editReply({ content: `⚠️ **You already have an active free key!**\n\n🆔 **Key ID:** \`${existingUser.keyId}\`\n🔑 **Key:** \`${existingUser.password}\`` });
            }

            const randomLetters = Array.from({length: 6}, () => String.fromCharCode(65 + Math.floor(Math.random() * 26))).join('');
            const password = `LUAS-FREE-${randomLetters}`;
            const uniqueKeyId = Math.floor(100000 + Math.random() * 900000).toString(); 
            
            const newUser = new UserModel({
                username: "luas",
                password: password,
                keyId: uniqueKeyId,
                plan: "free",
                duration: "Lifetime",
                discordId: interaction.user.id
            });
            await newUser.save();

            const dmEmbed = new EmbedBuilder()
                .setColor('#2B2D31')
                .setTitle('🎉 Free Key Generated')
                .setDescription(`🚀 **Key -->** \`${password}\`\n` +
                                `🆔 **Key ID -->** \`${uniqueKeyId}\`\n` +
                                `🪄 **Generated By -->** <@${interaction.user.id}>\n` +
                                `👑 **Key Owner -->** <@${interaction.user.id}>\n` +
                                `📝 **Reason -->** Free Access\n` +
                                `⏰ **Generation Time -->** <t:${Math.floor(Date.now() / 1000)}:F>\n` +
                                `⏱️ **Expiration -->** \`Lifetime\`\n\n` +
                                `❗️ \`Warning!!\` __**THE KEY IS SINGLE USE, DO NOT SHARE IT WITH ANYONE**__`)
                .setFooter({ text: 'Luas • Automatic Delivery System' })
                .setTimestamp();

            const logChannelId = process.env.LOG_CHANNEL_ID;
            if (logChannelId) {
                const logChannel = interaction.client.channels.cache.get(logChannelId);
                if (logChannel) await logChannel.send({ embeds: [dmEmbed] }).catch(() => {});
            }

            try {
                await interaction.user.send({ embeds: [dmEmbed] });
                await interaction.editReply({ content: "✅ **Key successfully generated! Please check your DMs.**" });
            } catch (e) {
                await interaction.editReply({ embeds: [dmEmbed] });
            }
        } catch (err) {
            console.error(err);
            await interaction.editReply({ content: "❌ **An error occurred.**" });
        }
    }
};